### ISSUE TITLE
Peter is at your service

### ISSUE THREAD

**Issue by happypeter** [Wellaiyo/Wellaiyo.github.io#1]
看起来进展良好，恭喜！

有问题可以在本仓库 （ repo ) 下提 issue，@ 我一下我就能看到了。

**Comment by happypeter** [comment]
@Wellaiyo 你那边用 github 随度怎么样？我在家里有时候会比较慢

所以有问题也可以注册一个 http://gitcafe.com 的账号，到那上面提 ticket，跟这边的 issue 是一样的。@happypeter 就行了。我在那边也有账号：https://gitcafe.com/happypeter

gitcafe 是国内的，所以速度会比较快。

**Comment by Wellaiyo** [comment]
@happypeter 能从线上网站所能看到的代码中看出网站后台是用什么语言开发的吗？
我想了解下优步uber.com是用什么后台语言开发的

**Comment by Wellaiyo** [comment]
我感觉最近github登陆状况好多了

**Comment by happypeter** [comment]
这个是看不出来的。不过，从前台的代码的结构，缓存策略，url 结构，可以大略的去猜一下是否是用了 Rails 。 uber 应该不是 Rails，但是他们也是要全战的人：https://www.uber.com/jobs/4767

**Comment by happypeter** [comment]
他们 js 用的比较多：https://github.com/uber

**Comment by Wellaiyo** [comment]
看到了，貌似有PHP、Python，我一开始还以为用的nodejs

**Comment by Wellaiyo** [comment]
@happypeter 
Hi, Peter
最近过得还不错吧，我到杭州工作已经一个月了，随着经验的增多，我再次抛开了以前那些比较low的想法。比如对Git工作模式的偏见、对Rails的否定.....
我已经开始喜欢上Git了，也在学习js各种前沿框架，接触Python这样的语言，打算过段时间还是得回头再学习一下Rails。经验增加了以后，我发现学习这些东西并没有什么难的，越学越能发现其中的趣味。
再次感谢你当初对我的指导，非常的有用，让我见识到一个全新的web开发的世界。
大牛，你真棒！
Thanks!

**Comment by happypeter** [comment]
看你发的图片了，用新的  Mac 机器了。Rails 确实很牛，代表 web 开发的各种新趋势，其实 python 也好 php nodejs 社区也好，很多内容都是跟 rails 学的。

**Comment by Wellaiyo** [comment]
对，python中的django框架和rails很像的，今天看朋友圈里一篇文章，2015年框架排名中，angularjs第一，ruby on rails第二 ，django第四 .......  我估计这是国外的排名， 国内rails应该没这么火

**Comment by happypeter** [comment]
我觉得也是

**Comment by Wellaiyo** [comment]
@happypeter 听上次你说要在imooc讲SVG课程 ，大概什么时候能出呀 ，等了一段时间了。
我想找到一个利用SVG解决一些图表或者图标或者动画的问题的最佳实践，期待你的精彩讲解！

**Comment by happypeter** [comment]
两周前就发给他们了，什么时候发布就要等等了

**Comment by Wellaiyo** [comment]
好的 
你最近还会接单做吗？有没有单子多余呀，我这边可以帮忙做的，前端或者完整项目都行

**Comment by happypeter** [comment]
最近都在录制课程，没有接单
