### ISSUE TITLE
关于web开发社区的创建

### ISSUE THREAD

**Issue by Wellaiyo** [Wellaiyo/Wellaiyo.github.io#6]
@happypeter 我们学校的老师同意咱们的这种想法，并能提供一定的帮助 。现在的问题是如何找到这些有兴趣的人，把他们组织起来

**Comment by happypeter** [comment]
新建一个 qq 群，428190544

燕鸣网站开发互助组，


可以让感兴趣的同学加入，咱们先帮大家回答一些问题，赞赞人气。

**Comment by Wellaiyo** [comment]
我觉得西区人可能会多一点 ，因为燕大的经济管理系都在西区，老师也在西区。这边找场地估计也好找点。我正在联系人。。。。

**Comment by Wellaiyo** [comment]
老师的意思是全力支持 ，难点就在于吸引这些人的兴趣拉拢他们

**Comment by happypeter** [comment]
有老师支持那就肯定能行。我觉得有下面几点咱们可以到时候见面商量敲定一下：

- 技术栈选型。我第一支持的是 Rails，如果是 nodejs 也支持。PHP 也还好，毕竟用的人多。这个不定下来后面学生的问题就会非常分散，精力耗费会很大

- 社区游戏规则。能否每周有固定的地点可以见面？比如可以每次聚会一部分时间讲课，另一部分时间讨论。

能够定下一些内容之后，那么活动也就有了主题，大家看看主题大概就知道咱们是干什么的了，这样不管是通过 qq 群推广，还是其他方法也都会旗帜比较鲜明一些。

**Comment by Wellaiyo** [comment]
恩 ，这个思路非常棒！  你先加我QQ群 ，我没加进去

**Comment by Wellaiyo** [comment]
你周末有时间吗？  见面时间最好定在周末 ，因为怕人多，有的人有重要的课。 关于见面地点的话，我看看能不能固定时间申请个教室用来上课的

**Comment by happypeter** [comment]
加你进群了

**Comment by happypeter** [comment]
周末可以的

**Comment by Wellaiyo** [comment]
@happypeter  看来这些人不好引导 ，要不就是他们压根就没决心先干好一件事

**Comment by happypeter** [comment]
当你要追一个女生的时候，并不是说你第一次请吃饭她拒绝了，就表示她肯定不会喜欢你。最事情要有足够的热情才能打动别人的。
